app = "la-virtual-zone"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = "80"
    handlers = ["http"]

  [[services.ports]]
    port = "443"
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 800
    type = "connections"

  [[services.http_checks]]
    path = "/health"
    protocol = "http"
    interval = "30s"
    timeout = "5s"