// Script para cargar los jugadores proporcionados
const jugadoresData = [
  {
    id: 1,
    nombre_jugador: "Luis",
    apellido_jugador: "Maximiano",
    edad: 26,
    altura: "190cm",
    peso: "84kg",
    pierna: "Derecho",
    estilo_juego: "Portero Ofensivo",
    posicion: "Pt",
    valoracion: 78,
    precio_compra_libre: 44,
    actitud_ofensiva: 50,
    control_balon: 65,
    drible: 60,
    posesion_balon: 55,
    pase_raso: 65,
    pase_bombeado: 65,
    finalizacion: 50,
    cabeceador: 82,
    balon_parado: 50,
    efecto: 50,
    velocidad: 65,
    aceleracion: 65,
    potencia_tiro: 75,
    salto: 78,
    contacto_fisico: 82,
    equilibrio: 65,
    resistencia: 68,
    actitud_defensiva: 65,
    recuperacion_balon: 50,
    agresividad: 50,
    actitud_portero: 85,
    atajar_pt: 84,
    despejar_pt: 84,
    reflejos_pt: 88,
    cobertura_pt: 84,
    uso_pie_malo: 3,
    precision_pie_malo: 4,
    estabilidad: 5,
    resistencia_lesiones: 3,
    foto_jugador: "",
    is_free: true,
    nacionalidad: "Portugal",
    id_equipo: null
  },
  {
    id: 2,
    nombre_jugador: "Nnamdi",
    apellido_jugador: "Collins",
    edad: 21,
    altura: "191cm",
    peso: "88kg",
    pierna: "Derecho",
    estilo_juego: "",
    posicion: "Dec",
    valoracion: 78,
    precio_compra_libre: 44,
    actitud_ofensiva: 65,
    control_balon: 70,
    drible: 78,
    posesion_balon: 70,
    pase_raso: 68,
    pase_bombeado: 65,
    finalizacion: 58,
    cabeceador: 75,
    balon_parado: 58,
    efecto: 60,
    velocidad: 85,
    aceleracion: 82,
    potencia_tiro: 70,
    salto: 85,
    contacto_fisico: 82,
    equilibrio: 65,
    resistencia: 75,
    actitud_defensiva: 82,
    recuperacion_balon: 80,
    agresividad: 80,
    actitud_portero: 40,
    atajar_pt: 40,
    despejar_pt: 40,
    reflejos_pt: 40,
    cobertura_pt: 40,
    uso_pie_malo: 2,
    precision_pie_malo: 2,
    estabilidad: 4,
    resistencia_lesiones: 2,
    foto_jugador: "",
    is_free: true,
    nacionalidad: "Alemania",
    id_equipo: null
  },
  {
    id: 3,
    nombre_jugador: "Lukas",
    apellido_jugador: "Hradecky",
    edad: 35,
    altura: "192cm",
    peso: "82kg",
    pierna: "Derecho",
    estilo_juego: "Portero Defensivo",
    posicion: "Pt",
    valoracion: 80,
    precio_compra_libre: 56,
    actitud_ofensiva: 50,
    control_balon: 60,
    drible: 50,
    posesion_balon: 60,
    pase_raso: 60,
    pase_bombeado: 60,
    finalizacion: 50,
    cabeceador: 82,
    balon_parado: 55,
    efecto: 55,
    velocidad: 65,
    aceleracion: 65,
    potencia_tiro: 78,
    salto: 78,
    contacto_fisico: 82,
    equilibrio: 65,
    resistencia: 65,
    actitud_defensiva: 60,
    agresividad: 50,
    actitud_portero: 88,
    atajar_pt: 85,
    despejar_pt: 85,
    reflejos_pt: 85,
    cobertura_pt: 88,
    uso_pie_malo: 1,
    precision_pie_malo: 3,
    estabilidad: 6,
    resistencia_lesiones: 2,
    foto_jugador: "",
    is_free: true,
    nacionalidad: "Finlandia",
    id_equipo: null
  },
  {
    id: 4,
    nombre_jugador: "Konstantinos",
    apellido_jugador: "Koulierakis",
    edad: 21,
    altura: "188cm",
    peso: "78kg",
    pierna: "Izquierdo",
    estilo_juego: "Creación",
    posicion: "Dec",
    valoracion: 80,
    precio_compra_libre: 56,
    actitud_ofensiva: 62,
    control_balon: 70,
    drible: 68,
    posesion_balon: 70,
    pase_raso: 70,
    pase_bombeado: 70,
    finalizacion: 60,
    cabeceador: 80,
    balon_parado: 60,
    efecto: 65,
    velocidad: 75,
    aceleracion: 75,
    potencia_tiro: 78,
    salto: 84,
    contacto_fisico: 85,
    equilibrio: 68,
    resistencia: 75,
    actitud_defensiva: 84,
    recuperacion_balon: 84,
    agresividad: 84,
    actitud_portero: 40,
    atajar_pt: 40,
    despejar_pt: 40,
    reflejos_pt: 40,
    cobertura_pt: 40,
    uso_pie_malo: 2,
    precision_pie_malo: 1,
    estabilidad: 5,
    resistencia_lesiones: 2,
    foto_jugador: "",
    is_free: true,
    nacionalidad: "Grecia",
    id_equipo: null
  },
  {
    id: 5,
    nombre_jugador: "Bafodé",
    apellido_jugador: "Diakité",
    edad: 24,
    altura: "184cm",
    peso: "78kg",
    pierna: "Derecho",
    estilo_juego: "Lateral Defensivo",
    posicion: "Dec",
    valoracion: 80,
    precio_compra_libre: 56,
    actitud_ofensiva: 70,
    control_balon: 75,
    drible: 72,
    posesion_balon: 75,
    pase_raso: 75,
    pase_bombeado: 72,
    finalizacion: 60,
    cabeceador: 78,
    balon_parado: 58,
    efecto: 60,
    velocidad: 80,
    aceleracion: 75,
    potencia_tiro: 70,
    salto: 85,
    contacto_fisico: 78,
    equilibrio: 70,
    resistencia: 82,
    actitud_defensiva: 82,
    recuperacion_balon: 82,
    agresividad: 82,
    actitud_portero: 40,
    atajar_pt: 40,
    despejar_pt: 40,
    reflejos_pt: 40,
    cobertura_pt: 40,
    uso_pie_malo: 2,
    precision_pie_malo: 2,
    estabilidad: 5,
    resistencia_lesiones: 2,
    foto_jugador: "",
    is_free: true,
    nacionalidad: "Francia",
    id_equipo: null
  }
];

// Función para cargar los jugadores
function cargarJugadores() {
  try {
    // Obtener jugadores existentes
    const jugadoresExistentes = JSON.parse(localStorage.getItem('players') || '[]');
    
    // Agregar los nuevos jugadores
    const todosLosJugadores = [...jugadoresExistentes, ...jugadoresData];
    
    // Guardar en localStorage
    localStorage.setItem('players', JSON.stringify(todosLosJugadores));
    
    console.log(`✅ Se cargaron ${jugadoresData.length} jugadores exitosamente`);
    console.log(`📊 Total de jugadores en el sistema: ${todosLosJugadores.length}`);
    
    return true;
  } catch (error) {
    console.error('❌ Error al cargar jugadores:', error);
    return false;
  }
}

// Ejecutar la carga
if (typeof window !== 'undefined') {
  cargarJugadores();
}

export { cargarJugadores, jugadoresData };
